### PR TITLE
Fix mangled shebang

### PR DESCRIPTION
**Pull request by dwrobel**

### CODE REVIEW

**Comment by ArcEye** [comment]
Author not whitelisted yet - can one of the admins verify this patch?

**Comment by luminize** [comment]
Ok to test

**Comment by ArcEye** [comment]
This file should not be in machinekit-cnc.
It already exists in machinekit-hal and cannot be in both, I will fix this

**Comment by ArcEye** [comment]
I remembered incorrectly.
I left it in `cnc` and removed from `hal`, as it was only going to be called from a combined package situation.
How the `!` got mislaid and how it worked without it is another matter :frowning_face:

**Pull request merged**
